### ISSUE TITLE
Typo in TestTask.groovy

### ISSUE THREAD

**Issue by 80586** [creising/soapui-gradle-plugin#1]
Hello,

There is a typo in the soapui-gradle-plugin. In src/main/groovy/io/byteshifter/plugins/soapui/tasks/TestTask.groovy, line 213, projectProperties() should be getProjectProperties().

This causes the setting of the projectProperties key in the soapui -> test closure to throw a NullPointerException.

Diff: http://pastie.org/private/uwjrxzbzclx93dld2riozg

**Comment by creising** [comment]
Thanks for creating the issue. I pushed up the fix.
